
settingVersions:
  recommendedSettingsVersion: 'default'
  recommendedSettingsLabels: ['default', 'simulation']

setting:
  default:
    type: 'sim'
  simulation:
    type: 'sim'
    avg_seeing: 0.5
    std_seeing: 0.1
    chance_failure: 0.0
