{% set data= load_setup_py_data() %}
package:
  name: "ts-dimm"
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  noarch: generic
  entry_points:
    - run_dimm_csc = lsst.ts.dimm.dimm_csc:run_dimm_csc

test:
  requires:
    - sqlalchemy
    - ts-conda-build =0.4
    - ts-xml {{ xml_conda_version }}
    - ts-salobj {{ salobj_version }}
    - ts-tcpip
  source_files:
    - bin
    - pyproject.toml
    - python
    - setup.cfg
    - tests
  commands:
    - pytest

requirements:
  host:
    - pip
    - python {{ python }}
    - setuptools
    - setuptools_scm
  build:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-conda-build =0.4
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - sqlalchemy
    - ts-xml
    - ts-salobj
    - ts-tcpip
